### ISSUE TITLE
translated string in module

### ISSUE THREAD

**Issue by Manfred62** [nvidoni/MarkupWeather#3]
Hi Nikola,

check line 179 in the module. There's german text (Aktuelles Wetter...) inside. Should be made translatable?
```php
$out .= "<div class='location'><h3>Aktuelles Wetter in " . $location[0]['city'] . "</h3><span>" . iconv('ISO-8859-2', 'UTF-8', strftime($this->date, strtotime(date("d.m.Y.")))) . "</span></div>";
```

**Comment by nvidoni** [comment]
That was accidentally pulled from pull request, I've removed it because initally it displays only City/Location + date.
