### ISSUE TITLE
add translatable strings

### ISSUE THREAD

**Issue by Manfred62** [nvidoni/MarkupWeather#4]
Hi Nikola,

to make it complete, you can make 2 additional strings translatable:
line 227 and  234:
```php
$field->label = __("Set Locale", __FILE__);
$field->label = __("Date Format", __FILE__);
```

**Comment by nvidoni** [comment]
Hi Manfred62,

I've made proposed changes, I forgot to put translatable strings into the code a while ago when I made the module...

Thx!
